### PR TITLE
Various unlock / send style fixes

### LINKED ISSUE #189: Send / Modal Style Regressions
This is probably my fault from the v3 style import, but the spacing is all janky now. This is just an issue to make sure I don't forget to fix this.

screen shot 2017-09-12 at 2 44 01 pm

screen shot 2017-09-12 at 2 46 31 pm

screen shot 2017-09-12 at 2 46 59 pm

### PR DESCRIPTION
**Pull request by wbobeirne**
Closes #189. Fixes some weird spacing in the deterministic wallet modal (Not pictured), the send transaction modal at smaller sizes, and the hanging send transaction button.

---

screen shot 2017-10-28 at 10 24 25 am

---

screen shot 2017-10-28 at 2 10 44 pm

### CODE REVIEW

File: common/containers/Tabs/SendTransaction/components/ConfirmationModal.tsx [hunk 1]
```diff
@@ -101,84 +101,87 @@ class ConfirmationModal extends React.Component<Props, State> {
...
+                    <li className="ConfModal-details-detail">
+                      You are sending{' '}
+                      <strong>
+                        {value} {symbol}
+                      </strong>{' '}
+                      with a gas price of <strong>{gasPrice} gwei</strong>
+                    </li>
+                    <li className="ConfModal-details-detail">
+                      You are interacting with the
+                      <strong>{node.network}</strong>{' '}
```
Comment (dternyak) [inline common/containers/Tabs/SendTransaction/components/ConfirmationModal.tsx]: `{' '}` before `{node.network}` to address whitespace issue in screenshot

Comment (wbobeirne) [reply common/containers/Tabs/SendTransaction/components/ConfirmationModal.tsx]: Good catch!
